### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by kobaje** [1rfsNet/Fritz-Box-Cloudflare-DynDNS#1]
Hallo,

ich habe alles wie beschrieben installiert. Das php liegt auf meinem privaten Webserver und ist erreichbar. Im Log der Fritzbox steht der Fehler "DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler 103 - SSL Failure". Es entsteht kein Eintrag im Log deines Scripts wenn die FB einen IP-wechsel macht.

Wenn ich den Update-Link (vervollständigt mit Token und Domain) im Browser aufrufe bekomme ich im Log auf dem Webserver die meldung "Authentication failed".

Ich komme leider nicht mehr weiter, Hoffe auf deine Hilfe.

Grüße und danke 

Jens

**Comment by 1rfsNet** [comment]
Hi,

dieser Fehler ist bei mir nie aufgetreten, aber üblicherweise weißt "Der DynDNS-Anbieter meldet Fehler" auf ein Problem mit dem Webserver hin. Die FritzBox bekommt aktuell keine Rückmeldung vom Script (ist in Planung), sondern du bekommst die Infos nur im Log.
Ich habe das Script selbst noch nie mit SSL/HTTPS getestet, aber grundsätzlich spricht da nichts dagegen. Hast du ein echtes SSL Zertifikat oder ein selbst signiertes? 

"Authentication failed" ist nochmal ein anderes Problem. Es bedeutet, dass die Authentifizierung bei Cloudflare nicht geklappt hat (z.B. der API-Token ist falsch, die Zone ungültig, Rechteproblem bei den Einstellungen für den API-Token, etc.).

VG
